const environments = {
  mock: {
    app_bundle_id: 'com.pyypl.mock',
    scheme: 'pyypl.mock://',
    api: 'https://api.dev.pyypl.io',
  },
  dev: {
    app_bundle_id: 'com.pyypl.dev',
    scheme: 'pyypl.dev://',
    api: 'https://api.dev.pyypl.io',
  },
  stg: {
    app_bundle_id: 'com.pyypl.stg',
    scheme: 'pyypl.stg://',
    api: 'https://api.stg.pyypl.io',
  },
  prd: {
    app_bundle_id: 'com.pyypl',
    scheme: 'pyypl://',
    api: 'https://api.pyypl.io',
  },
};

const countries = {
  1: {
    code: '+1',
    commonCode: '001',
    countryCode: 'US',
    countryName: 'United States',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.US',
    value: '1',
  },
  7: {
    code: '+7',
    commonCode: '007',
    countryCode: 'RU',
    countryName: 'Russia',
    currency: 'RUB',
    currencyName: 'Russian Rouble',
    labelMsgId: 'countryCodes.RU',
    value: '7',
  },
  20: {
    code: '+20',
    commonCode: '0020',
    countryCode: 'EG',
    countryName: 'Egypt',
    currency: 'EGP',
    currencyName: 'Egyptian Pound',
    labelMsgId: 'countryCodes.EG',
    value: '20',
  },
  27: {
    code: '+27',
    commonCode: '0027',
    countryCode: 'ZA',
    countryName: 'South Africa',
    currency: 'ZAR',
    currencyName: 'South African Rand',
    labelMsgId: 'countryCodes.ZA',
    value: '27',
  },
  30: {
    code: '+30',
    commonCode: '0030',
    countryCode: 'GR',
    countryName: 'Greece',
    currency: 'EUR',
    currencyName: 'Euro',
    labelMsgId: 'countryCodes.GR',
    value: '30',
  },
  31: {
    code: '+31',
    commonCode: '0031',
    countryCode: 'NL',
    countryName: 'Netherlands',
    currency: 'EUR',
    currencyName: 'Euro',
    labelMsgId: 'countryCodes.NL',
    value: '31',
  },
  32: {
    code: '+32',
    commonCode: '0032',
    countryCode: 'BE',
    countryName: 'Belgium',
    currency: 'EUR',
    currencyName: 'Euro',
    labelMsgId: 'countryCodes.BE',
    value: '32',
  },
  33: {
    code: '+33',
    commonCode: '0033',
    countryCode: 'FR',
    countryName: 'France',
    currency: 'EUR',
    currencyName: 'Euro',
    labelMsgId: 'countryCodes.FR',
    value: '33',
  },
  34: {
    code: '+34',
    commonCode: '0034',
    countryCode: 'ES',
    countryName: 'Spain',
    currency: 'EUR',
    currencyName: 'Euro',
    labelMsgId: 'countryCodes.ES',
    value: '34',
  },
  36: {
    code: '+36',
    commonCode: '0036',
    countryCode: 'HU',
    countryName: 'Hungary',
    currency: 'HUF',
    currencyName: 'Hungarian Forint',
    labelMsgId: 'countryCodes.HU',
    value: '36',
  },
  39: {
    code: '+39',
    commonCode: '0039',
    countryCode: 'IT',
    countryName: 'Italy',
    currency: 'EUR',
    currencyName: 'Euro',
    labelMsgId: 'countryCodes.IT',
    value: '39',
  },
  40: {
    code: '+40',
    commonCode: '0040',
    countryCode: 'RO',
    countryName: 'Romania',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.RO',
    value: '40',
  },
  41: {
    code: '+41',
    commonCode: '0041',
    countryCode: 'CH',
    countryName: 'Switzerland',
    currency: 'CHF',
    currencyName: 'Swiss Franc',
    labelMsgId: 'countryCodes.CH',
    value: '41',
  },
  43: {
    code: '+43',
    commonCode: '0043',
    countryCode: 'AT',
    countryName: 'Austria',
    currency: 'EUR',
    currencyName: 'Euro',
    labelMsgId: 'countryCodes.AT',
    value: '43',
  },
  44: {
    code: '+44',
    commonCode: '0044',
    countryCode: 'GB',
    countryName: 'United Kingdom',
    currency: 'GBP',
    currencyName: 'Pound Sterling',
    labelMsgId: 'countryCodes.GB',
    value: '44',
  },
  45: {
    code: '+45',
    commonCode: '0045',
    countryCode: 'DK',
    countryName: 'Denmark',
    currency: 'DKK',
    currencyName: 'Danish Krone',
    labelMsgId: 'countryCodes.DK',
    value: '45',
  },
  46: {
    code: '+46',
    commonCode: '0046',
    countryCode: 'SE',
    countryName: 'Sweden',
    currency: 'SEK',
    currencyName: 'Swedish Krona',
    labelMsgId: 'countryCodes.SE',
    value: '46',
  },
  47: {
    code: '+47',
    commonCode: '0047',
    countryCode: 'NO',
    countryName: 'Norway',
    currency: 'NOK',
    currencyName: 'Norwegian Krone',
    labelMsgId: 'countryCodes.NO',
    value: '47',
  },
  48: {
    code: '+48',
    commonCode: '0048',
    countryCode: 'PL',
    countryName: 'Poland',
    currency: 'PLN',
    currencyName: 'Polish Zloty',
    labelMsgId: 'countryCodes.PL',
    value: '48',
  },
  49: {
    code: '+49',
    commonCode: '0049',
    countryCode: 'DE',
    countryName: 'Germany',
    currency: 'EUR',
    currencyName: 'Euro',
    labelMsgId: 'countryCodes.DE',
    value: '49',
  },
  51: {
    code: '+51',
    commonCode: '0051',
    countryCode: 'PE',
    countryName: 'Peru',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.PE',
    value: '51',
  },
  52: {
    code: '+52',
    commonCode: '0052',
    countryCode: 'MX',
    countryName: 'Mexico',
    currency: 'MXN',
    currencyName: 'Mexican Peso',
    labelMsgId: 'countryCodes.MX',
    value: '52',
  },
  53: {
    code: '+53',
    commonCode: '0053',
    countryCode: 'CU',
    countryName: 'Cuba',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.CU',
    value: '53',
  },
  54: {
    code: '+54',
    commonCode: '0054',
    countryCode: 'AR',
    countryName: 'Argentina',
    currency: 'ARS',
    currencyName: 'Argentine Peso',
    labelMsgId: 'countryCodes.AR',
    value: '54',
  },
  55: {
    code: '+55',
    commonCode: '0055',
    countryCode: 'BR',
    countryName: 'Brazil',
    currency: 'BRL',
    currencyName: 'Brazilian Real',
    labelMsgId: 'countryCodes.BR',
    value: '55',
  },
  56: {
    code: '+56',
    commonCode: '0056',
    countryCode: 'CL',
    countryName: 'Chile',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.CL',
    value: '56',
  },
  57: {
    code: '+57',
    commonCode: '0057',
    countryCode: 'CO',
    countryName: 'Colombia',
    currency: 'COP',
    currencyName: 'Colombian Peso',
    labelMsgId: 'countryCodes.CO',
    value: '57',
  },
  58: {
    code: '+58',
    commonCode: '0058',
    countryCode: 'VE',
    countryName: 'Venezuela',
    currency: 'VEB',
    currencyName: 'Venezuelan Bolivar',
    labelMsgId: 'countryCodes.VE',
    value: '58',
  },
  60: {
    code: '+60',
    commonCode: '0060',
    countryCode: 'MY',
    countryName: 'Malaysia',
    currency: 'MYR',
    currencyName: 'Malaysian Ringgit',
    labelMsgId: 'countryCodes.MY',
    value: '60',
  },
  61: {
    code: '+61',
    commonCode: '0061',
    countryCode: 'CC',
    countryName: 'Cocos (Keeling) Islands',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.CC',
    value: '61',
  },
  62: {
    code: '+62',
    commonCode: '0062',
    countryCode: 'ID',
    countryName: 'Indonesia',
    currency: 'IDR',
    currencyName: 'Indonesian Rupiah',
    labelMsgId: 'countryCodes.ID',
    value: '62',
  },
  63: {
    code: '+63',
    commonCode: '0063',
    countryCode: 'PH',
    countryName: 'Philippines',
    currency: 'PHP',
    currencyName: 'Philippine Peso',
    labelMsgId: 'countryCodes.PH',
    value: '63',
  },
  64: {
    code: '+64',
    commonCode: '0064',
    countryCode: 'NZ',
    countryName: 'New Zealand',
    currency: 'NZD',
    currencyName: 'New Zealand Dollar',
    labelMsgId: 'countryCodes.NZ',
    value: '64',
  },
  65: {
    code: '+65',
    commonCode: '0065',
    countryCode: 'SG',
    countryName: 'Singapore',
    currency: 'SGD',
    currencyName: 'Singapore Dollar',
    labelMsgId: 'countryCodes.SG',
    value: '65',
  },
  66: {
    code: '+66',
    commonCode: '0066',
    countryCode: 'TH',
    countryName: 'Thailand',
    currency: 'THB',
    currencyName: 'Thai Baht',
    labelMsgId: 'countryCodes.TH',
    value: '66',
  },
  81: {
    code: '+81',
    commonCode: '0081',
    countryCode: 'JP',
    countryName: 'Japan',
    currency: 'JPY',
    currencyName: 'Japanese Yen',
    labelMsgId: 'countryCodes.JP',
    value: '81',
  },
  82: {
    code: '+82',
    commonCode: '0082',
    countryCode: 'KR',
    countryName: 'South Korea',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.KR',
    value: '82',
  },
  84: {
    code: '+84',
    commonCode: '0084',
    countryCode: 'VN',
    countryName: 'VietNam',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.VN',
    value: '84',
  },
  86: {
    code: '+86',
    commonCode: '0086',
    countryCode: 'CN',
    countryName: 'China',
    currency: 'CNY',
    currencyName: 'Chinese Yuan',
    labelMsgId: 'countryCodes.CN',
    value: '86',
  },
  90: {
    code: '+90',
    commonCode: '0090',
    countryCode: 'TR',
    countryName: 'Turkey',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.TR',
    value: '90',
  },
  91: {
    code: '+91',
    commonCode: '0091',
    countryCode: 'IN',
    countryName: 'India',
    currency: 'INR',
    currencyName: 'Indian Rupee',
    labelMsgId: 'countryCodes.IN',
    value: '91',
  },
  92: {
    code: '+92',
    commonCode: '0092',
    countryCode: 'PK',
    countryName: 'Pakistan',
    currency: 'PKR',
    currencyName: 'Pakistani Rupee',
    labelMsgId: 'countryCodes.PK',
    value: '92',
  },
  93: {
    code: '+93',
    commonCode: '0093',
    countryCode: 'AF',
    countryName: 'Afghanistan',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.AF',
    value: '93',
  },
  94: {
    code: '+94',
    commonCode: '0094',
    countryCode: 'LK',
    countryName: 'Sri Lanka',
    currency: 'LKR',
    currencyName: 'Sri Lanka Rupee',
    labelMsgId: 'countryCodes.LK',
    value: '94',
  },
  95: {
    code: '+95',
    commonCode: '0095',
    countryCode: 'MM',
    countryName: 'Myanmar',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.MM',
    value: '95',
  },
  98: {
    code: '+98',
    commonCode: '0098',
    countryCode: 'IR',
    countryName: 'Iran',
    currency: 'IRR',
    currencyName: 'Iran Rial',
    labelMsgId: 'countryCodes.IR',
    value: '98',
  },
  211: {
    code: '+211',
    commonCode: '00211',
    countryCode: 'SS',
    countryName: 'South Sudan',
    currency: '',
    currencyName: '',
    labelMsgId: 'countryCodes.SS',
    value: '211',
  },
  212: {
    code: '+212',
    commonCode: '00212',
    countryCode: 'EH',
    countryName: 'Western Sahara',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.EH',
    value: '212',
  },
  213: {
    code: '+213',
    commonCode: '00213',
    countryCode: 'DZ',
    countryName: 'Algeria',
    currency: 'DZD',
    currencyName: 'Algerian Dinar',
    labelMsgId: 'countryCodes.DZ',
    value: '213',
  },
  216: {
    code: '+216',
    commonCode: '00216',
    countryCode: 'TN',
    countryName: 'Tunisia',
    currency: 'TND',
    currencyName: 'Tunisian Dinar',
    labelMsgId: 'countryCodes.TN',
    value: '216',
  },
  218: {
    code: '+218',
    commonCode: '00218',
    countryCode: 'LY',
    countryName: 'Libya',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.LY',
    value: '218',
  },
  220: {
    code: '+220',
    commonCode: '00220',
    countryCode: 'GM',
    countryName: 'Gambia',
    currency: 'GMD',
    currencyName: 'Gambian Dalasi',
    labelMsgId: 'countryCodes.GM',
    value: '220',
  },
  221: {
    code: '+221',
    commonCode: '00221',
    countryCode: 'SN',
    countryName: 'Senegal',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.SN',
    value: '221',
  },
  222: {
    code: '+222',
    commonCode: '00222',
    countryCode: 'MR',
    countryName: 'Mauritania',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.MR',
    value: '222',
  },
  223: {
    code: '+223',
    commonCode: '00223',
    countryCode: 'ML',
    countryName: 'Mali',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.ML',
    value: '223',
  },
  224: {
    code: '+224',
    commonCode: '00224',
    countryCode: 'GN',
    countryName: 'Guinea',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.GN',
    value: '224',
  },
  225: {
    code: '+225',
    commonCode: '00225',
    countryCode: 'CI',
    countryName: "Côte D'Ivoire",
    currency: 'XOF',
    currencyName: 'CFA Franc',
    labelMsgId: 'countryCodes.CI',
    value: '225',
  },
  226: {
    code: '+226',
    commonCode: '00226',
    countryCode: 'BF',
    countryName: 'Burkina Faso',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.BF',
    value: '226',
  },
  227: {
    code: '+227',
    commonCode: '00227',
    countryCode: 'NE',
    countryName: 'Niger',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.NE',
    value: '227',
  },
  228: {
    code: '+228',
    commonCode: '00228',
    countryCode: 'TG',
    countryName: 'Togo',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.TG',
    value: '228',
  },
  229: {
    code: '+229',
    commonCode: '00229',
    countryCode: 'BJ',
    countryName: 'Benin',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.BJ',
    value: '229',
  },
  230: {
    code: '+230',
    commonCode: '00230',
    countryCode: 'MU',
    countryName: 'Mauritius',
    currency: 'MUR',
    currencyName: 'Mauritius Rupee',
    labelMsgId: 'countryCodes.MU',
    value: '230',
  },
  231: {
    code: '+231',
    commonCode: '00231',
    countryCode: 'LR',
    countryName: 'Liberia',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.LR',
    value: '231',
  },
  232: {
    code: '+232',
    commonCode: '00232',
    countryCode: 'SL',
    countryName: 'Sierra Leone',
    currency: 'SLE',
    currencyName: 'Sierra Leonean Leone',
    labelMsgId: 'countryCodes.SL',
    value: '232',
  },
  233: {
    code: '+233',
    commonCode: '00233',
    countryCode: 'GH',
    countryName: 'Ghana',
    currency: 'GHC',
    currencyName: 'Ghanian Cedi',
    labelMsgId: 'countryCodes.GH',
    value: '233',
  },
  234: {
    code: '+234',
    commonCode: '00234',
    countryCode: 'NG',
    countryName: 'Nigeria',
    currency: 'NGN',
    currencyName: 'Nigerian Naira',
    labelMsgId: 'countryCodes.NG',
    value: '234',
  },
  235: {
    code: '+235',
    commonCode: '00235',
    countryCode: 'TD',
    countryName: 'Chad',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.TD',
    value: '235',
  },
  236: {
    code: '+236',
    commonCode: '00236',
    countryCode: 'CF',
    countryName: 'Central African Republic',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.CF',
    value: '236',
  },
  237: {
    code: '+237',
    commonCode: '00237',
    countryCode: 'CM',
    countryName: 'Cameroon',
    currency: 'XAF',
    currencyName: 'CFA Franc',
    labelMsgId: 'countryCodes.CM',
    value: '237',
  },
  238: {
    code: '+238',
    commonCode: '00238',
    countryCode: 'CV',
    countryName: 'Cape Verde',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.CV',
    value: '238',
  },
  239: {
    code: '+239',
    commonCode: '00239',
    countryCode: 'ST',
    countryName: 'Sao Tome and Principe',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.ST',
    value: '239',
  },
  240: {
    code: '+240',
    commonCode: '00240',
    countryCode: 'GQ',
    countryName: 'Equatorial Guinea',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.GQ',
    value: '240',
  },
  241: {
    code: '+241',
    commonCode: '00241',
    countryCode: 'GA',
    countryName: 'Gabon',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.GA',
    value: '241',
  },
  242: {
    code: '+242',
    commonCode: '00242',
    countryCode: 'CG',
    countryName: 'Congo',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.CG',
    value: '242',
  },
  243: {
    code: '+243',
    commonCode: '00243',
    countryCode: 'CD',
    countryName: 'Democratic Republic of the Congo',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.CD',
    value: '243',
  },
  244: {
    code: '+244',
    commonCode: '00244',
    countryCode: 'AO',
    countryName: 'Angola',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.AO',
    value: '244',
  },
  245: {
    code: '+245',
    commonCode: '00245',
    countryCode: 'GW',
    countryName: 'Guinea-Bissau',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.GW',
    value: '245',
  },
  246: {
    code: '+246',
    commonCode: '00246',
    countryCode: 'IO',
    countryName: 'British Indian Ocean Territory',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.IO',
    value: '246',
  },
  248: {
    code: '+248',
    commonCode: '00248',
    countryCode: 'SC',
    countryName: 'Seychelles',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.SC',
    value: '248',
  },
  249: {
    code: '+249',
    commonCode: '00249',
    countryCode: 'SD',
    countryName: 'Sudan',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.SD',
    value: '249',
  },
  250: {
    code: '+250',
    commonCode: '00250',
    countryCode: 'RW',
    countryName: 'Rwanda',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.RW',
    value: '250',
  },
  251: {
    code: '+251',
    commonCode: '00251',
    countryCode: 'ET',
    countryName: 'Ethiopia',
    currency: 'ETB',
    currencyName: 'Ethiopian Birr',
    labelMsgId: 'countryCodes.ET',
    value: '251',
  },
  252: {
    code: '+252',
    commonCode: '00252',
    countryCode: 'SO',
    countryName: 'Somalia',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.SO',
    value: '252',
  },
  253: {
    code: '+253',
    commonCode: '00253',
    countryCode: 'DJ',
    countryName: 'Djibouti',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.DJ',
    value: '253',
  },
  254: {
    code: '+254',
    commonCode: '00254',
    countryCode: 'KE',
    countryName: 'Kenya',
    currency: 'KES',
    currencyName: 'Kenyan Shilling',
    labelMsgId: 'countryCodes.KE',
    value: '254',
  },
  255: {
    code: '+255',
    commonCode: '00255',
    countryCode: 'TZ',
    countryName: 'Tanzania',
    currency: 'TZS',
    currencyName: 'Tanzanian Shilling',
    labelMsgId: 'countryCodes.TZ',
    value: '255',
  },
  256: {
    code: '+256',
    commonCode: '00256',
    countryCode: 'UG',
    countryName: 'Uganda',
    currency: 'UGX',
    currencyName: 'Ugandan Shilling',
    labelMsgId: 'countryCodes.UG',
    value: '256',
  },
  257: {
    code: '+257',
    commonCode: '00257',
    countryCode: 'BI',
    countryName: 'Burundi',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.BI',
    value: '257',
  },
  258: {
    code: '+258',
    commonCode: '00258',
    countryCode: 'MZ',
    countryName: 'Mozambique',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.MZ',
    value: '258',
  },
  260: {
    code: '+260',
    commonCode: '00260',
    countryCode: 'ZM',
    countryName: 'Zambia',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.ZM',
    value: '260',
  },
  261: {
    code: '+261',
    commonCode: '00261',
    countryCode: 'MG',
    countryName: 'Madagascar',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.MG',
    value: '261',
  },
  262: {
    code: '+262',
    commonCode: '00262',
    countryCode: 'RE',
    countryName: 'Réunion',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.RE',
    value: '262',
  },
  263: {
    code: '+263',
    commonCode: '00263',
    countryCode: 'ZW',
    countryName: 'Zimbabwe',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.ZW',
    value: '263',
  },
  264: {
    code: '+264',
    commonCode: '00264',
    countryCode: 'NA',
    countryName: 'Namibia',
    currency: 'NAD',
    currencyName: 'Namibian Dollar',
    labelMsgId: 'countryCodes.NA',
    value: '264',
  },
  265: {
    code: '+265',
    commonCode: '00265',
    countryCode: 'MW',
    countryName: 'Malawi',
    currency: 'MWK',
    currencyName: 'Malawi Kwacha',
    labelMsgId: 'countryCodes.MW',
    value: '265',
  },
  266: {
    code: '+266',
    commonCode: '00266',
    countryCode: 'LS',
    countryName: 'Lesotho',
    currency: 'ZAR',
    currencyName: 'South African Rand',
    labelMsgId: 'countryCodes.LS',
    value: '266',
  },
  267: {
    code: '+267',
    commonCode: '00267',
    countryCode: 'BW',
    countryName: 'Botswana',
    currency: 'BWP',
    currencyName: 'Botswana Pula',
    labelMsgId: 'countryCodes.BW',
    value: '267',
  },
  268: {
    code: '+268',
    commonCode: '00268',
    countryCode: 'SZ',
    countryName: 'Swaziland',
    currency: 'SZL',
    currencyName: 'Swaziland Lilageni',
    labelMsgId: 'countryCodes.SZ',
    value: '268',
  },
  269: {
    code: '+269',
    commonCode: '00269',
    countryCode: 'KM',
    countryName: 'Comoros',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.KM',
    value: '269',
  },
  291: {
    code: '+291',
    commonCode: '00291',
    countryCode: 'ER',
    countryName: 'Eritrea',
    currency: 'ERN',
    currencyName: 'Eritrea Nakfa',
    labelMsgId: 'countryCodes.ER',
    value: '291',
  },
  297: {
    code: '+297',
    commonCode: '00297',
    countryCode: 'AW',
    countryName: 'Aruba',
    currency: 'AWG',
    currencyName: 'Aruba Florin',
    labelMsgId: 'countryCodes.AW',
    value: '297',
  },
  298: {
    code: '+298',
    commonCode: '00298',
    countryCode: 'FO',
    countryName: 'Faroe Islands',
    currency: 'DKK',
    currencyName: 'Danish Krone',
    labelMsgId: 'countryCodes.FO',
    value: '298',
  },
  299: {
    code: '+299',
    commonCode: '00299',
    countryCode: 'GL',
    countryName: 'Greenland',
    currency: 'DKK',
    currencyName: 'Danish Krone',
    labelMsgId: 'countryCodes.GL',
    value: '299',
  },
  350: {
    code: '+350',
    commonCode: '00350',
    countryCode: 'GI',
    countryName: 'Gibraltar',
    currency: 'GBP',
    currencyName: 'British Pound',
    labelMsgId: 'countryCodes.GI',
    value: '350',
  },
  351: {
    code: '+351',
    commonCode: '00351',
    countryCode: 'PT',
    countryName: 'Portugal',
    currency: 'EUR',
    currencyName: 'Euro',
    labelMsgId: 'countryCodes.PT',
    value: '351',
  },
  352: {
    code: '+352',
    commonCode: '00352',
    countryCode: 'LU',
    countryName: 'Luxembourg',
    currency: 'EUR',
    currencyName: 'Euro',
    labelMsgId: 'countryCodes.LU',
    value: '352',
  },
  353: {
    code: '+353',
    commonCode: '00353',
    countryCode: 'IE',
    countryName: 'Ireland',
    currency: 'EUR',
    currencyName: 'Euro',
    labelMsgId: 'countryCodes.IE',
    value: '353',
  },
  354: {
    code: '+354',
    commonCode: '00354',
    countryCode: 'IS',
    countryName: 'Iceland',
    currency: 'ISK',
    currencyName: 'Iceland Krona',
    labelMsgId: 'countryCodes.IS',
    value: '354',
  },
  355: {
    code: '+355',
    commonCode: '00355',
    countryCode: 'AL',
    countryName: 'Albania',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.AL',
    value: '355',
  },
  356: {
    code: '+356',
    commonCode: '00356',
    countryCode: 'MT',
    countryName: 'Malta',
    currency: 'EUR',
    currencyName: 'Euro',
    labelMsgId: 'countryCodes.MT',
    value: '356',
  },
  357: {
    code: '+357',
    commonCode: '00357',
    countryCode: 'CY',
    countryName: 'Cyprus',
    currency: 'EUR',
    currencyName: 'Euro',
    labelMsgId: 'countryCodes.CY',
    value: '357',
  },
  358: {
    code: '+358',
    commonCode: '00358',
    countryCode: 'AX',
    countryName: 'Åland Islands',
    currency: '',
    currencyName: '',
    labelMsgId: 'countryCodes.AX',
    value: '358',
  },
  359: {
    code: '+359',
    commonCode: '00359',
    countryCode: 'BG',
    countryName: 'Bulgaria',
    currency: 'BGN',
    currencyName: 'Bulgarian Lev',
    labelMsgId: 'countryCodes.BG',
    value: '359',
  },
  370: {
    code: '+370',
    commonCode: '00370',
    countryCode: 'LT',
    countryName: 'Lithuania',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.LT',
    value: '370',
  },
  371: {
    code: '+371',
    commonCode: '00371',
    countryCode: 'LV',
    countryName: 'Latvia',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.LV',
    value: '371',
  },
  372: {
    code: '+372',
    commonCode: '00372',
    countryCode: 'EE',
    countryName: 'Estonia',
    currency: 'EUR',
    currencyName: 'Euro',
    labelMsgId: 'countryCodes.EE',
    value: '372',
  },
  373: {
    code: '+373',
    commonCode: '00373',
    countryCode: 'MD',
    countryName: 'Moldova',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.MD',
    value: '373',
  },
  374: {
    code: '+374',
    commonCode: '00374',
    countryCode: 'AM',
    countryName: 'Armenia',
    currency: 'AMD',
    currencyName: 'Armenian Dram',
    labelMsgId: 'countryCodes.AM',
    value: '374',
  },
  375: {
    code: '+375',
    commonCode: '00375',
    countryCode: 'BY',
    countryName: 'Belarus',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.BY',
    value: '375',
  },
  376: {
    code: '+376',
    commonCode: '00376',
    countryCode: 'AD',
    countryName: 'Andorra',
    currency: 'EUR',
    currencyName: 'Euro',
    labelMsgId: 'countryCodes.AD',
    value: '376',
  },
  377: {
    code: '+377',
    commonCode: '00377',
    countryCode: 'MC',
    countryName: 'Monaco',
    currency: 'EUR',
    currencyName: 'Euro',
    labelMsgId: 'countryCodes.MC',
    value: '377',
  },
  378: {
    code: '+378',
    commonCode: '00378',
    countryCode: 'SM',
    countryName: 'San Marino',
    currency: 'EUR',
    currencyName: 'Euro',
    labelMsgId: 'countryCodes.SM',
    value: '378',
  },
  379: {
    code: '+379',
    commonCode: '00379',
    countryCode: 'VA',
    countryName: 'Vatican City',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.VA',
    value: '379',
  },
  380: {
    code: '+380',
    commonCode: '00380',
    countryCode: 'UA',
    countryName: 'Ukraine',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.UA',
    value: '380',
  },
  381: {
    code: '+381',
    commonCode: '00381',
    countryCode: 'RS',
    countryName: 'Serbia',
    currency: '',
    currencyName: '',
    labelMsgId: 'countryCodes.RS',
    value: '381',
  },
  382: {
    code: '+382',
    commonCode: '00382',
    countryCode: 'ME',
    countryName: 'Montenegro',
    currency: '',
    currencyName: '',
    labelMsgId: 'countryCodes.ME',
    value: '382',
  },
  383: {
    code: '+383',
    commonCode: '00383',
    countryCode: 'XK',
    countryName: 'Kosovo',
    currency: '',
    currencyName: '',
    labelMsgId: 'countryCodes.XK',
    value: '383',
  },
  385: {
    code: '+385',
    commonCode: '00385',
    countryCode: 'HR',
    countryName: 'Croatia',
    currency: 'HRK',
    currencyName: 'Croatian Kuna',
    labelMsgId: 'countryCodes.HR',
    value: '385',
  },
  386: {
    code: '+386',
    commonCode: '00386',
    countryCode: 'SI',
    countryName: 'Slovenia',
    currency: 'EUR',
    currencyName: 'Euro',
    labelMsgId: 'countryCodes.SI',
    value: '386',
  },
  387: {
    code: '+387',
    commonCode: '00387',
    countryCode: 'BA',
    countryName: 'Bosnia and Herzegovina',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.BA',
    value: '387',
  },
  389: {
    code: '+389',
    commonCode: '00389',
    countryCode: 'MK',
    countryName: 'Macedonia',
    currency: 'MKD',
    currencyName: 'Macedonian Denar',
    labelMsgId: 'countryCodes.MK',
    value: '389',
  },
  420: {
    code: '+420',
    commonCode: '00420',
    countryCode: 'CZ',
    countryName: 'Czech Republic',
    currency: 'CZK',
    currencyName: 'Czech Koruna',
    labelMsgId: 'countryCodes.CZ',
    value: '420',
  },
  421: {
    code: '+421',
    commonCode: '00421',
    countryCode: 'SK',
    countryName: 'Slovakia',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.SK',
    value: '421',
  },
  423: {
    code: '+423',
    commonCode: '00423',
    countryCode: 'LI',
    countryName: 'Liechtenstein',
    currency: 'CHF',
    currencyName: 'Swiss Franc',
    labelMsgId: 'countryCodes.LI',
    value: '423',
  },
  500: {
    code: '+500',
    commonCode: '00500',
    countryCode: 'FK',
    countryName: 'Falkland Islands (Malvinas)',
    currency: 'FKP',
    currencyName: 'Falkland Islands Pound',
    labelMsgId: 'countryCodes.FK',
    value: '500',
  },
  501: {
    code: '+501',
    commonCode: '00501',
    countryCode: 'BZ',
    countryName: 'Belize',
    currency: 'BZD',
    currencyName: 'Belize Dollar',
    labelMsgId: 'countryCodes.BZ',
    value: '501',
  },
  502: {
    code: '+502',
    commonCode: '00502',
    countryCode: 'GT',
    countryName: 'Guatemala',
    currency: 'GTQ',
    currencyName: 'Guatemala Quetzal',
    labelMsgId: 'countryCodes.GT',
    value: '502',
  },
  503: {
    code: '+503',
    commonCode: '00503',
    countryCode: 'SV',
    countryName: 'El Salvador',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.SV',
    value: '503',
  },
  504: {
    code: '+504',
    commonCode: '00504',
    countryCode: 'HN',
    countryName: 'Honduras',
    currency: 'HNL',
    currencyName: 'Honduras Lempira',
    labelMsgId: 'countryCodes.HN',
    value: '504',
  },
  505: {
    code: '+505',
    commonCode: '00505',
    countryCode: 'NI',
    countryName: 'Nicaragua',
    currency: 'NIO',
    currencyName: 'Nicaragua Cordoba',
    labelMsgId: 'countryCodes.NI',
    value: '505',
  },
  506: {
    code: '+506',
    commonCode: '00506',
    countryCode: 'CR',
    countryName: 'Costa Rica',
    currency: 'CRC',
    currencyName: 'Costa Rica Colon',
    labelMsgId: 'countryCodes.CR',
    value: '506',
  },
  507: {
    code: '+507',
    commonCode: '00507',
    countryCode: 'PA',
    countryName: 'Panama',
    currency: 'PAB',
    currencyName: 'Panama Balboa',
    labelMsgId: 'countryCodes.PA',
    value: '507',
  },
  508: {
    code: '+508',
    commonCode: '00508',
    countryCode: 'PM',
    countryName: 'Saint Pierre and Miquelon',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.PM',
    value: '508',
  },
  509: {
    code: '+509',
    commonCode: '00509',
    countryCode: 'HT',
    countryName: 'Haiti',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.HT',
    value: '509',
  },
  590: {
    code: '+590',
    commonCode: '00590',
    countryCode: 'MF',
    countryName: 'Saint Martin (French Part)',
    currency: '',
    currencyName: '',
    labelMsgId: 'countryCodes.MF',
    value: '590',
  },
  591: {
    code: '+591',
    commonCode: '00591',
    countryCode: 'BO',
    countryName: 'Bolivia',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.BO',
    value: '591',
  },
  593: {
    code: '+593',
    commonCode: '00593',
    countryCode: 'EC',
    countryName: 'Ecuador',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.EC',
    value: '593',
  },
  594: {
    code: '+594',
    commonCode: '00594',
    countryCode: 'GF',
    countryName: 'French Guiana',
    currency: 'EUR',
    currencyName: 'Euro',
    labelMsgId: 'countryCodes.GF',
    value: '594',
  },
  595: {
    code: '+595',
    commonCode: '00595',
    countryCode: 'PY',
    countryName: 'Paraguay',
    currency: 'PYG',
    currencyName: 'Paraguayan Guarani',
    labelMsgId: 'countryCodes.PY',
    value: '595',
  },
  596: {
    code: '+596',
    commonCode: '00596',
    countryCode: 'MQ',
    countryName: 'Martinique',
    currency: 'EUR',
    currencyName: 'Euro',
    labelMsgId: 'countryCodes.MQ',
    value: '596',
  },
  597: {
    code: '+597',
    commonCode: '00597',
    countryCode: 'SR',
    countryName: 'Suriname',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.SR',
    value: '597',
  },
  598: {
    code: '+598',
    commonCode: '00598',
    countryCode: 'UY',
    countryName: 'Uruguay',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.UY',
    value: '598',
  },
  599: {
    code: '+599',
    commonCode: '00599',
    countryCode: 'SX',
    countryName: 'Sint Maarten (Dutch Part)',
    currency: '',
    currencyName: '',
    labelMsgId: 'countryCodes.SX',
    value: '599',
  },
  670: {
    code: '+670',
    commonCode: '00670',
    countryCode: 'TL',
    countryName: 'Timor-Leste',
    currency: '',
    currencyName: '',
    labelMsgId: 'countryCodes.TL',
    value: '670',
  },
  672: {
    code: '+672',
    commonCode: '00672',
    countryCode: 'NF',
    countryName: 'Norfolk Island',
    currency: 'AUD',
    currencyName: 'Australian Dollar',
    labelMsgId: 'countryCodes.NF',
    value: '672',
  },
  673: {
    code: '+673',
    commonCode: '00673',
    countryCode: 'BN',
    countryName: 'Brunei Darussalam',
    currency: 'BND',
    currencyName: 'Brunei Dollar',
    labelMsgId: 'countryCodes.BN',
    value: '673',
  },
  674: {
    code: '+674',
    commonCode: '00674',
    countryCode: 'NR',
    countryName: 'Nauru',
    currency: 'AUD',
    currencyName: 'Australian Dollar',
    labelMsgId: 'countryCodes.NR',
    value: '674',
  },
  675: {
    code: '+675',
    commonCode: '00675',
    countryCode: 'PG',
    countryName: 'Papua New Guinea',
    currency: 'PGK',
    currencyName: 'Papua New Guinea Kina',
    labelMsgId: 'countryCodes.PG',
    value: '675',
  },
  676: {
    code: '+676',
    commonCode: '00676',
    countryCode: 'TO',
    countryName: 'Tonga',
    currency: 'TOP',
    currencyName: "Tonga Pa'anga",
    labelMsgId: 'countryCodes.TO',
    value: '676',
  },
  677: {
    code: '+677',
    commonCode: '00677',
    countryCode: 'SB',
    countryName: 'Solomon Islands',
    currency: 'SBD',
    currencyName: 'Solomon Islands Dollar',
    labelMsgId: 'countryCodes.SB',
    value: '677',
  },
  678: {
    code: '+678',
    commonCode: '00678',
    countryCode: 'VU',
    countryName: 'Vanuatu',
    currency: 'VUV',
    currencyName: 'Vanuatu Vatu',
    labelMsgId: 'countryCodes.VU',
    value: '678',
  },
  679: {
    code: '+679',
    commonCode: '00679',
    countryCode: 'FJ',
    countryName: 'Fiji',
    currency: 'FJD',
    currencyName: 'Fiji Dollar',
    labelMsgId: 'countryCodes.FJ',
    value: '679',
  },
  680: {
    code: '+680',
    commonCode: '00680',
    countryCode: 'PW',
    countryName: 'Palau',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.PW',
    value: '680',
  },
  681: {
    code: '+681',
    commonCode: '00681',
    countryCode: 'WF',
    countryName: 'Wallis and Futuna',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.WF',
    value: '681',
  },
  682: {
    code: '+682',
    commonCode: '00682',
    countryCode: 'CK',
    countryName: 'Cook Islands',
    currency: 'NZD',
    currencyName: 'New Zealand Dollar',
    labelMsgId: 'countryCodes.CK',
    value: '682',
  },
  683: {
    code: '+683',
    commonCode: '00683',
    countryCode: 'NU',
    countryName: 'Niue',
    currency: 'NZD',
    currencyName: 'New Zealand Dollar',
    labelMsgId: 'countryCodes.NU',
    value: '683',
  },
  685: {
    code: '+685',
    commonCode: '00685',
    countryCode: 'WS',
    countryName: 'Samoa',
    currency: 'WST',
    currencyName: 'Samoa Tala',
    labelMsgId: 'countryCodes.WS',
    value: '685',
  },
  686: {
    code: '+686',
    commonCode: '00686',
    countryCode: 'KI',
    countryName: 'Kiribati',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.KI',
    value: '686',
  },
  687: {
    code: '+687',
    commonCode: '00687',
    countryCode: 'NC',
    countryName: 'New Caledonia',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.NC',
    value: '687',
  },
  688: {
    code: '+688',
    commonCode: '00688',
    countryCode: 'TV',
    countryName: 'Tuvalu',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.TV',
    value: '688',
  },
  689: {
    code: '+689',
    commonCode: '00689',
    countryCode: 'PF',
    countryName: 'French Polynesia',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.PF',
    value: '689',
  },
  690: {
    code: '+690',
    commonCode: '00690',
    countryCode: 'TK',
    countryName: 'Tokelau',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.TK',
    value: '690',
  },
  691: {
    code: '+691',
    commonCode: '00691',
    countryCode: 'FM',
    countryName: 'Micronesia',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.FM',
    value: '691',
  },
  692: {
    code: '+692',
    commonCode: '00692',
    countryCode: 'MH',
    countryName: 'Marshall Islands',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.MH',
    value: '692',
  },
  850: {
    code: '+850',
    commonCode: '00850',
    countryCode: 'KP',
    countryName: 'North Korea',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.KP',
    value: '850',
  },
  852: {
    code: '+852',
    commonCode: '00852',
    countryCode: 'HK',
    countryName: 'Hong Kong',
    currency: 'HKD',
    currencyName: 'Hong Kong Dollar',
    labelMsgId: 'countryCodes.HK',
    value: '852',
  },
  853: {
    code: '+853',
    commonCode: '00853',
    countryCode: 'MO',
    countryName: 'Macao',
    currency: 'MOP',
    currencyName: 'Macau Pataca',
    labelMsgId: 'countryCodes.MO',
    value: '853',
  },
  855: {
    code: '+855',
    commonCode: '00855',
    countryCode: 'KH',
    countryName: 'Cambodia',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.KH',
    value: '855',
  },
  856: {
    code: '+856',
    commonCode: '00856',
    countryCode: 'LA',
    countryName: "Lao People's Democratic Republic",
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.LA',
    value: '856',
  },
  880: {
    code: '+880',
    commonCode: '00880',
    countryCode: 'BD',
    countryName: 'Bangladesh',
    currency: 'BDT',
    currencyName: 'Bangladesh Taka',
    labelMsgId: 'countryCodes.BD',
    value: '880',
  },
  886: {
    code: '+886',
    commonCode: '00886',
    countryCode: 'TW',
    countryName: 'Taiwan',
    currency: 'TWD',
    currencyName: 'Taiwan Dollar',
    labelMsgId: 'countryCodes.TW',
    value: '886',
  },
  960: {
    code: '+960',
    commonCode: '00960',
    countryCode: 'MV',
    countryName: 'Maldives',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.MV',
    value: '960',
  },
  961: {
    code: '+961',
    commonCode: '00961',
    countryCode: 'LB',
    countryName: 'Lebanon',
    currency: 'LBP',
    currencyName: 'Lebanese Pound',
    labelMsgId: 'countryCodes.LB',
    value: '961',
  },
  962: {
    code: '+962',
    commonCode: '00962',
    countryCode: 'JO',
    countryName: 'Jordan',
    currency: 'JOD',
    currencyName: 'Jordanian Dinar',
    labelMsgId: 'countryCodes.JO',
    value: '962',
  },
  963: {
    code: '+963',
    commonCode: '00963',
    countryCode: 'SY',
    countryName: 'Syrian Arab Republic',
    currency: 'SYP',
    currencyName: 'Syrian Pound',
    labelMsgId: 'countryCodes.SY',
    value: '963',
  },
  964: {
    code: '+964',
    commonCode: '00964',
    countryCode: 'IQ',
    countryName: 'Iraq',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.IQ',
    value: '964',
  },
  965: {
    code: '+965',
    commonCode: '00965',
    countryCode: 'KW',
    countryName: 'Kuwait',
    currency: 'KWD',
    currencyName: 'Kuwaiti Dinar',
    labelMsgId: 'countryCodes.KW',
    value: '965',
  },
  966: {
    code: '+966',
    commonCode: '00966',
    countryCode: 'SA',
    countryName: 'Saudi Arabia',
    currency: 'SAR',
    currencyName: 'Saudi Arabian Riyal',
    labelMsgId: 'countryCodes.SA',
    value: '966',
  },
  967: {
    code: '+967',
    commonCode: '00967',
    countryCode: 'YE',
    countryName: 'Yemen',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.YE',
    value: '967',
  },
  968: {
    code: '+968',
    commonCode: '00968',
    countryCode: 'OM',
    countryName: 'Oman',
    currency: 'OMR',
    currencyName: 'Omani Rial',
    labelMsgId: 'countryCodes.OM',
    value: '968',
  },
  970: {
    code: '+970',
    commonCode: '00970',
    countryCode: 'PS',
    countryName: 'Palestinian Territory',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.PS',
    value: '970',
  },
  971: {
    code: '+971',
    commonCode: '00971',
    countryCode: 'AE',
    countryName: 'United Arab Emirates',
    currency: 'AED',
    currencyName: 'UAE Dirham',
    labelMsgId: 'countryCodes.AE',
    value: '971',
  },
  972: {
    code: '+972',
    commonCode: '00972',
    countryCode: 'IL',
    countryName: 'Israel',
    currency: 'ILS',
    currencyName: 'Israeli Shekel',
    labelMsgId: 'countryCodes.IL',
    value: '972',
  },
  973: {
    code: '+973',
    commonCode: '00973',
    countryCode: 'BH',
    countryName: 'Bahrain',
    currency: 'BHD',
    currencyName: 'Bahraini Dinar',
    labelMsgId: 'countryCodes.BH',
    value: '973',
  },
  974: {
    code: '+974',
    commonCode: '00974',
    countryCode: 'QA',
    countryName: 'Qatar',
    currency: 'QAR',
    currencyName: 'Qatar Rial',
    labelMsgId: 'countryCodes.QA',
    value: '974',
  },
  975: {
    code: '+975',
    commonCode: '00975',
    countryCode: 'BT',
    countryName: 'Bhutan',
    currency: 'BTN',
    currencyName: 'Bhutan Ngultrum',
    labelMsgId: 'countryCodes.BT',
    value: '975',
  },
  976: {
    code: '+976',
    commonCode: '00976',
    countryCode: 'MN',
    countryName: 'Mongolia',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.MN',
    value: '976',
  },
  977: {
    code: '+977',
    commonCode: '00977',
    countryCode: 'NP',
    countryName: 'Nepal',
    currency: 'NPR',
    currencyName: 'Nepalese Rupee',
    labelMsgId: 'countryCodes.NP',
    value: '977',
  },
  992: {
    code: '+992',
    commonCode: '00992',
    countryCode: 'TJ',
    countryName: 'Tajikistan',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.TJ',
    value: '992',
  },
  993: {
    code: '+993',
    commonCode: '00993',
    countryCode: 'TM',
    countryName: 'Turkmenistan',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.TM',
    value: '993',
  },
  994: {
    code: '+994',
    commonCode: '00994',
    countryCode: 'AZ',
    countryName: 'Azerbaijan',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.AZ',
    value: '994',
  },
  995: {
    code: '+995',
    commonCode: '00995',
    countryCode: 'GE',
    countryName: 'Georgia',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.GE',
    value: '995',
  },
  996: {
    code: '+996',
    commonCode: '00996',
    countryCode: 'KG',
    countryName: 'Kyrgyzstan',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.KG',
    value: '996',
  },
  998: {
    code: '+998',
    commonCode: '00998',
    countryCode: 'UZ',
    countryName: 'Uzbekistan',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.UZ',
    value: '998',
  },
  1268: {
    code: '+1268',
    commonCode: '001268',
    countryCode: 'AG',
    countryName: 'Antigua and Barbuda',
    currency: 'XCD',
    currencyName: 'East Caribbean Dollar',
    labelMsgId: 'countryCodes.AG',
    value: '1268',
  },
  1664: {
    code: '+1664',
    commonCode: '001664',
    countryCode: 'MS',
    countryName: 'Montserrat',
    currency: 'XCD',
    currencyName: 'East Caribbean Dollar',
    labelMsgId: 'countryCodes.MS',
    value: '1664',
  },
  '1 684': {
    code: '+1 684',
    commonCode: '001 684',
    countryCode: 'AS',
    countryName: 'American Samoa',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.AS',
    value: '1 684',
  },
  '1 264': {
    code: '+1 264',
    commonCode: '001 264',
    countryCode: 'AI',
    countryName: 'Anguilla',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.AI',
    value: '1 264',
  },
  '1 242': {
    code: '+1 242',
    commonCode: '001 242',
    countryCode: 'BS',
    countryName: 'Bahamas',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.BS',
    value: '1 242',
  },
  '1 246': {
    code: '+1 246',
    commonCode: '001 246',
    countryCode: 'BB',
    countryName: 'Barbados',
    currency: 'BBD',
    currencyName: 'Barbados Dollar',
    labelMsgId: 'countryCodes.BB',
    value: '1 246',
  },
  '1 441': {
    code: '+1 441',
    commonCode: '001 441',
    countryCode: 'BM',
    countryName: 'Bermuda',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.BM',
    value: '1 441',
  },
  ' 345': {
    code: '+ 345',
    commonCode: '00 345',
    countryCode: 'KY',
    countryName: 'Cayman Islands',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.KY',
    value: ' 345',
  },
  '1 767': {
    code: '+1 767',
    commonCode: '001 767',
    countryCode: 'DM',
    countryName: 'Dominica',
    currency: 'XCD',
    currencyName: 'East Caribbean Dollar',
    labelMsgId: 'countryCodes.DM',
    value: '1 767',
  },
  '1 849': {
    code: '+1 849',
    commonCode: '001 849',
    countryCode: 'DO',
    countryName: 'Dominican Republic',
    currency: 'DOP',
    currencyName: 'Dominican Peso',
    labelMsgId: 'countryCodes.DO',
    value: '1 849',
  },
  '1 473': {
    code: '+1 473',
    commonCode: '001 473',
    countryCode: 'GD',
    countryName: 'Grenada',
    currency: 'XCD',
    currencyName: 'East Caribbean Dollar',
    labelMsgId: 'countryCodes.GD',
    value: '1 473',
  },
  '1 671': {
    code: '+1 671',
    commonCode: '001 671',
    countryCode: 'GU',
    countryName: 'Guam',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.GU',
    value: '1 671',
  },
  '1 876': {
    code: '+1 876',
    commonCode: '001 876',
    countryCode: 'JM',
    countryName: 'Jamaica',
    currency: 'JMD',
    currencyName: 'Jamaican Dollar',
    labelMsgId: 'countryCodes.JM',
    value: '1 876',
  },
  '1 670': {
    code: '+1 670',
    commonCode: '001 670',
    countryCode: 'MP',
    countryName: 'Northern Mariana Islands',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.MP',
    value: '1 670',
  },
  '1 939': {
    code: '+1 939',
    commonCode: '001 939',
    countryCode: 'PR',
    countryName: 'Puerto Rico',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.PR',
    value: '1 939',
  },
  '1 869': {
    code: '+1 869',
    commonCode: '001 869',
    countryCode: 'KN',
    countryName: 'Saint Kitts and Nevis',
    currency: 'XCD',
    currencyName: 'East Caribbean Dollar',
    labelMsgId: 'countryCodes.KN',
    value: '1 869',
  },
  '1 758': {
    code: '+1 758',
    commonCode: '001 758',
    countryCode: 'LC',
    countryName: 'Saint Lucia',
    currency: 'XCD',
    currencyName: 'East Caribbean Dollar',
    labelMsgId: 'countryCodes.LC',
    value: '1 758',
  },
  '1 784': {
    code: '+1 784',
    commonCode: '001 784',
    countryCode: 'VC',
    countryName: 'Saint Vincent and The Grenadines',
    currency: 'XCD',
    currencyName: 'East Caribbean Dollar',
    labelMsgId: 'countryCodes.VC',
    value: '1 784',
  },
  '1 868': {
    code: '+1 868',
    commonCode: '001 868',
    countryCode: 'TT',
    countryName: 'Trinidad and Tobago',
    currency: 'TTD',
    currencyName: 'Trinidad&Tobago Dollar',
    labelMsgId: 'countryCodes.TT',
    value: '1 868',
  },
  '1 649': {
    code: '+1 649',
    commonCode: '001 649',
    countryCode: 'TC',
    countryName: 'Turks and Caicos Islands',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.TC',
    value: '1 649',
  },
  '1 284': {
    code: '+1 284',
    commonCode: '001 284',
    countryCode: 'VG',
    countryName: 'Virgin Islands, British',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.VG',
    value: '1 284',
  },
  '1 340': {
    code: '+1 340',
    commonCode: '001 340',
    countryCode: 'VI',
    countryName: 'Virgin Islands, U.S.',
    currency: 'USD',
    currencyName: 'U.S. Dollar',
    labelMsgId: 'countryCodes.VI',
    value: '1 340',
  },
};

const bank_cards = {
  5000186622346654: {
    provider: 'checkout',
    valid: true,
    card_number: '5000186622346654',
    expiry_month: '12',
    expiry_year: '28',
    cvv: '257',
  },
  4658584090000001: {
    provider: 'checkout',
    valid: true,
    card_number: '4658584090000001',
    expiry_month: '12',
    expiry_year: '28',
    cvv: '257',
  },
  '0000000000000000': {
    provider: 'checkout',
    valid: false,
    card_number: '0000000000000000',
    expiry_month: '1',
    expiry_year: '24',
    cvv: '257',
  },
  5236000000000005: {
    provider: 'contact_pay',
    valid: true,
    card_number: '5236000000000005',
    expiry_month: '12',
    expiry_year: '28',
    cvv: '849',
  },
};

const users = {
  // United Arab Emirates
  971524790337: {
    phone_number: '524790337',
    passcode: '1111',
    country: countries['971'],
    currency: 'AED',
  },
  971561590101: {
    phone_number: '561590101',
    passcode: '1111',
    country: countries['971'],
    currency: 'AED',
  },
  971548899995: {
    phone_number: '548899995',
    passcode: '0000',
    country: countries['971'],
    currency: 'AED',
  },
  971548899999: {
    phone_number: '548899999',
    passcode: '0000',
    country: countries['971'],
    currency: 'AED',
  },
  971561530122: {
    phone_number: '561530122',
    passcode: '1111',
    country: countries['971'],
    currency: 'AED',
  },
  971561570201: {
    phone_number: '561570201',
    passcode: '1111',
    country: countries['971'],
    currency: 'AED',
  },
  971561570200: {
    phone_number: '561570200',
    passcode: '1111',
    country: countries['971'],
    currency: 'AED',
  },
  971561570199: {
    phone_number: '561570199',
    passcode: '1111',
    country: countries['971'],
    currency: 'AED',
  },
  // Uganda
  256751653671: {
    phone_number: '751653671',
    passcode: '1111',
    country: countries['256'],
    currency: 'UGX',
  },
  // Siera leone
  23276800012: {
    phone_number: '76800012',
    passcode: '0000',
    country: countries['232'],
    currency: 'SLE',
  },
  23225698036: {
    phone_number: '25698036',
    passcode: '1111',
    country: countries['232'],
    currency: 'SLE',
  },
  // Kenya
  254704040411: {
    phone_number: '704040411',
    passcode: '1111',
    country: countries['254'],
    currency: 'KES',
  },
  254705033052: {
    phone_number: '705033052',
    passcode: '1111',
    country: countries['254'],
    currency: 'KES',
  },
  254798765432: {
    phone_number: '705033052',
    passcode: '1111',
    country: countries['254'],
    currency: 'KES',
  },
  // India
  918722004410: {
    phone_number: '8722004410',
    passcode: '1111',
    country: countries['91'],
    currency: 'USD',
  },
  918722008802: {
    phone_number: '8722008802',
    passcode: '1111',
    country: countries['91'],
    currency: 'USD',
  },
  918722558874: {
    phone_number: '8722558874',
    passcode: '1111',
    country: countries['91'],
    currency: 'USD',
  },
  918722008801: {
    phone_number: '8722008801',
    passcode: '1111',
    country: countries['91'],
    currency: 'USD',
  },
  918087788990: {
    phone_number: '8087788990',
    passcode: '1111',
    country: countries['91'],
    currency: 'USD',
  },
  // Russia
  79885522000: {
    phone_number: '9885522000',
    passcode: '1111',
    country: countries['7'],
    currency: 'USD',
  },
  79876543210: {
    phone_number: '9885522000',
    passcode: '0000',
    country: countries['7'],
    currency: 'USD',
  },
  79888999888: {
    phone_number: '9888999888',
    passcode: '1111',
    country: countries['7'],
    currency: 'USD',
  },
  79876543210: {
    phone_number: '9876543210',
    passcode: '1111',
    country: countries['7'],
    currency: 'USD',
  },
  // Netherlands
  31613785407: {
    phone_number: '613785407',
    passcode: '0000',
    country: countries['31'],
    currency: 'USD',
  },
  31625335620: {
    phone_number: '625335620',
    passcode: '0000',
    country: countries['31'],
    currency: 'USD',
  },
  // Pakistan
  92518658820: {
    phone_number: '518658820',
    passcode: '0000',
    country: countries['92'],
    currency: 'USD',
  },
  92518658821: {
    phone_number: '518658821',
    passcode: '0000',
    country: countries['92'],
    currency: 'USD',
  },
  // Uganda
  256779648354: {
    phone_number: '779648354',
    passcode: '1111',
    country: countries['256'],
    currency: 'UGX',
  },
  // Sierra Leone
  23230242424: {
    phone_number: '30242424',
    passcode: '1111',
    country: countries['232'],
    currency: 'SLE',
  },
  // Philippines
  639122558800: {
    phone_number: '9122558800',
    passcode: '1234',
    country: countries['63'],
    currency: 'USD',
  },
  // Bangladesh
  8801402992903: {
    phone_number: '1402992903',
    passcode: '1111',
    country: countries['880'],
    currency: 'USD',
  },
  // Ghana
  233554478843: {
    phone_number: '554478843',
    passcode: '1111',
    country: countries['233'],
    currency: 'USD',
  },
  // Cameroon
  237676749990: {
    phone_number: '676749990',
    passcode: '1111',
    country: countries['237'],
    currency: 'USD',
  },
  // Senegal
  221338235470: {
    phone_number: '338235470',
    passcode: '1111',
    country: countries['221'],
    currency: 'USD',
  },
};

function generateRandomString(length) {
  var result = '';
  const characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
  const charactersLength = characters.length;
  for (var i = 0; i < length; i++) {
    result += characters.charAt(Math.floor(Math.random() * charactersLength));
  }
  return result;
}

function generatePhoneNumber(code) {
  if (code === 'AE') {
    var number = 520000000 + Math.floor(Math.random() * 8000000);
    return '971' + number;
  }
  if (code === 'IN') {
    var number = 8000000000 + Math.floor(Math.random() * 100000000);
    return '91' + number;
  }
  if (code === 'SL') {
    var number = 76000000 + Math.floor(Math.random() * 800000);
    return '232' + number;
  }
  if (code === 'GH') {
    var number = 550000000 + Math.floor(Math.random() * 8000000000);
    return '233' + number;
  }
  if (code === 'RU') {
    var number = 9800000000 + Math.floor(Math.random() * 8000000000);
    return '7' + number;
  }
}

// below are the defined default/dynamic variables
output.meta = environments[MAESTRO_ENV || 'mock']; // mock, dev, stg, prd

output.user = users[MAESTRO_USER || '971524790337']; // any user listed in https://dashboard.dev.pyypl.io/users and above

output.onboarding = users[MAESTRO_ONBOARDER || '']; // user should be listed above but not in https://dashboard.dev.pyypl.io/users

output.onboarding_country =
  users[
    MAESTRO_COUNTRY || generatePhoneNumber(output.user.country.countryCode)
  ];

output.change_language = {
  cases: {
    // TODO: define test cases for this feature
  },
  tests: {
    AE: [
      { level: 3, language: 'Arabic' },
      { level: 3, language: 'English' },
    ],
  },
};

//Covered for Android and for AE and INTL user
output.profile = {
  cases: {
    name: {
      level: 3,
      activated: true,
      data: {
        name_valid: 'Test user ' + generateRandomString(5),
      },
    },
    email: {
      level: 3,
      activated: true,
      data: {
        email_valid: generateRandomString(10) + '@pyypl.com',
      },
    },
    address_1: {
      level: 3,
      activated: true,
      data: {
        address_1_valid: generateRandomString(7),
      },
    },
    address_2: {
      level: 3,
      activated: true,
      data: {
        address_2_valid: generateRandomString(7),
      },
    },
    zip_code: {
      level: 3,
      activated: true,
      data: {
        zip_code_valid: generateRandomString(7),
      },
    },
    city: {
      level: 3,
      activated: true,
      data: {
        city_valid: generateRandomString(7),
      },
    },
  },
  tests: {
    AE: {
      level: 3,
    },
    RU: {
      level: 3,
    },
  },
};

output.invite_friend = {
  cases: {
    // TODO: define test cases for this feature
  },
  tests: {
    AE: {
      level: 3,
    },
    IN: {
      level: 3,
    },
  },
};

// TODO: listLoadMethods randomly times out sometimes? (BE issue)
//Covered for Android and iOS for AE and IN user
output.checkout = {
  cases: {
    // TODO: define test cases for this feature
    cards: {
      valid: bank_cards['5000186622346654'],
      invalid: bank_cards['0000000000000000'],
    },
    amounts: {
      valid: {
        AED: 100,
        USD: 25,
      },
      invalid: {
        minimum: {
          AED: 1,
          USD: 1,
        },
        maximum: {
          AED: 100000,
          USD: 10000,
        },
      },
    },
  },
  tests: {
    AE: [
      // TODO: there seems to be an issue when loading twice in a row quickly (FE issue)
      { level: 3, mode: 'card_new' },
      { level: 3, mode: 'card_saved' },
    ],
    IN: [
      { level: 3, mode: 'card_new' },
      { level: 3, mode: 'card_saved' },
    ],
  },
};

//Covered for Android and iOS
output.bank_manual = {
  cases: {
    // TODO: define test cases for this feature
    amounts: {
      valid: {
        AED: 100,
        USD: 25,
      },
      invalid: {
        minimum: {
          AED: 1,
          USD: 1,
        },
        maximum: {
          AED: 100000,
          USD: 10000,
        },
      },
    },
    transaction_ids: {
      valid: generateRandomString(6),
      invalid: 'X',
    },
  },
  tests: {
    AE: [{ level: 3 }],
  },
};

//Covered for Android and iOS for RU user only
output.contact_pay = {
  cases: {
    // TODO: define test cases for this feature
    cards: {
      valid: bank_cards['5236000000000005'],
      invalid: bank_cards['0000000000000000'],
    },
    amounts: {
      valid: {
        AED: 100,
        USD: 25,
      },
      invalid: {
        minimum: {
          AED: 1,
          USD: 1,
        },
        maximum: {
          AED: 100000,
          USD: 10000,
        },
      },
    },
  },
  tests: {
    RU: [{ level: 3 }],
  },
};

//Covered for iOS and GH, CM, SN users
output.mobile_wallets = {
  tests: {
    GH: [{ level: 1, wallet: 'AIRTEL/TIGO' }],
    CM: [{ level: 2, country: 'Cameroon', wallet: 'MTN' }],
    SN: [{ level: 2, country: 'Senegal', wallet: 'Orange Money' }],
  },
  cases: {
    // Unable to enter the mamount in decimal places
    // https://pyyplgroup.atlassian.net/browse/PSD-9229
    // minimum_amount: {
    //     level: 2,
    //     activated: true,
    //     data: {
    //         amount: {
    //             USD: 0.01,
    //         }
    //     }
    // },
    maximum_amount: {
      level: 2,
      activated: true,
      data: {
        amount: {
          USD: 99999999,
        },
      },
    },
    valid_amount: {
      level: 1,
      activated: true,
      data: {
        amount: {
          USD: 35, // minimum amount was 2USD earlier, changed to 35USd now
        },
      },
    },
    component_assertion: {
      level: 2,
      activated: true,
    },
  },
};

//Covered for iOS for all test{users & beneficiaries}
output.pyypl_to_pyypl = {
  tests: {
    // 971524790337
    AE: [
      { level: 3, beneficiary: users['971561570199'] }, // AE
      { level: 2, beneficiary: users['918722008802'] }, // IN
      { level: 1, beneficiary: users['23276800012'] }, // SL
      { level: 1, beneficiary: users['254704040411'] }, // KE
      // TODO: fix "no routes available" for Ugandan users (BE issue)
      // { level: 2, beneficiary: users["256751653671"] }, // UG
    ],
    // 79885522000
    //CAPTCHA TO BE REMOVED FROM RUSSIAN ACCOUNTS
    // RU: [
    //     { level: 3, beneficiary: users["79876543210"] }, // RU
    //     { level: 2, beneficiary: users["971561570199"] }, // AE
    //     { level: 1, beneficiary: users["254704040411"] }, // KE
    //     { level: 1, beneficiary: users["23276800012"] }, // SL
    // ],
    // 256779648354
    // UG: [
    //   { level: 2, beneficiary: users['256751653671'] }, // UG
    //   // TODO: other 3 routes not available for uganda (BE issue)
    //   // UGX to UAE
    //   // UGX to USD (India)
    //   // UGX to SLE
    // ],
    // // 23276800012
    // SL: [
    //   // Bug - "SL-SL p2p throws error transfer route not availble for unregistered users"
    //   { level: 2, beneficiary: users['23230242424'] }, // SL
    //   { level: 1, beneficiary: users['971561570199'] }, // AE
    //   { level: 1, beneficiary: users['918722008802'] }, // IN
    // ],
    // // 254798765432
    // KE: [
    //   { level: 2, beneficiary: users['254704040411'] }, // KE
    //   { level: 1, beneficiary: users['971561570199'] }, // AE
    //   { level: 1, beneficiary: users['918722008802'] }, // IN
    // ],
    // RU: [
    //   { level: 1, beneficiary: users['79888999888'] }, // RU
    // ],
  },
  cases: {
    unregistered: {
      level: 3,
      activated: true,
    },
    existing_contact: {
      level: 4,
      activated: true,
    },
    own_number: {
      level: 3,
      activated: true,
    },
    minimum_amount: {
      level: 2,
      activated: true,
      data: {
        amount: {
          AED: 0.01,
          USD: 1,
          UGX: 1,
          SLE: 1,
          KES: 1,
          RUS: 1,
        },
      },
    },
    maximum_amount: {
      level: 2,
      activated: true,
      data: {
        amount: {
          AED: 99999999,
          USD: 99999999,
          UGX: 99999999,
          SLE: 99999999,
          KES: 99999999,
          RUS: 99999999,
        },
      },
    },
    valid_amount: {
      level: 1,
      activated: true,
      data: {
        amount: {
          AED: 100,
          USD: 1,
          UGX: 500,
          SLE: 100,
          KES: 100,
          RUS: 100,
        },
      },
    },
    fees_not_applicable: {
      level: 2,
      activated: ['AE'].includes(output.user.country.countryCode),
      data: {
        amount: {
          AED: 99,
        },
      },
    },
    fees_applicable: {
      level: 2,
      activated: ['AE'].includes(output.user.country.countryCode),
      data: {
        amount: {
          AED: 100,
        },
      },
    },
    INTL_fees_applicable: {
      level: 2,
      activated: ['RU'].includes(output.user.country.countryCode),
      data: {
        amount: {
          RU: 100,
        },
      },
    },
    component_assertion: {
      level: 3,
      activated: true,
    },
  },
};

//Covered for iOS for AE users
output.remittance = {
  cases: {
    amount_screen_assertion: {
      level: 3,
      activated: true,
    },
    transaction_screen_assertion: {
      level: 3,
      activated: true,
    },
    amounts: {
      valid: {
        AED: 100,
        USD: 25,
        SLE: 100,
      },
      invalid: {
        minimum: {
          AED: 1,
          USD: 1,
          UGX: 1,
          SLE: 1,
          KES: 1,
          RUS: 1,
        },
        maximum: {
          AED: 1000000000,
          USD: 1000000000,
          UGX: 1000000000,
          SLE: 1000000000,
          KES: 1000000000,
          RUS: 1000000000,
        },
      },
    },
    ibans: {
      valid: generateRandomString(24),
      invalid: 'X',
    },
    document_numbers: {
      valid: generateRandomString(8),
      invalid: 'X',
    },
    data: {
      amounts: {
        valid: {
          AED: 100,
          USD: 25,
          SLE: 100,
        },
        invalid: {
          minimum: {
            AED: 1,
            USD: 1,
            UGX: 1,
            SLE: 1,
            KES: 1,
            RUS: 1,
          },
          maximum: {
            AED: 1000000000,
            USD: 1000000000,
            UGX: 1000000000,
            SLE: 1000000000,
            KES: 1000000000,
            RUS: 1000000000,
          },
        },
      },
      ibans: {
        valid: generateRandomString(24),
        invalid: 'X',
      },
      document_numbers: {
        valid: generateRandomString(8),
        invalid: 'X',
      },
    },
  },
  tests: {
    AE: [
      { level: 3, mode: 'bank', beneficiary: users['92518658821'] }, // PK
      { level: 3, mode: 'upi', beneficiary: users['918722004410'] }, // IN
      { level: 3, mode: 'cash', beneficiary: users['639122558800'] }, // PH
      { level: 3, mode: 'wallet', beneficiary: users['8801402992903'] }, //UG
    ],
    SL: [
      { level: 3, mode: 'bank', beneficiary: users['92518658821'] }, //PK
    ],
    KE: [
      { level: 3, mode: 'bank', beneficiary: users['92518658821'] }, //PK
    ],
  },
};

//Covered for Android and iOS AE user only
output.cards = {
  //Writing the logic to make the cards cases dynamic in case, as of now hard coded for UAE
  tests: {
    AE: [],
  },
  cases: {
    physical_card_request: {
      data: {
        address: 'SZR',
        fees: 30,
        city: 'Dubai',
      },
    },
    virtual_card: {
      data: {
        fees: 'AED 10.00',
      },
    },
    card_details: {
      data: {
        name1: 'ABDUL ALSAEDI',
        name2: 'John Doe',
        cardnumber: '6504 4900 0000 0208',
        last_4_digits: '0208',
        expiry: '01/29',
        cvv: '498',
      },
    },
  },
};

//Covered for Android and iOS IN & RU user
output.crypto = {
  tests: {
    IN: [
      {
        level: 1,
        bep20address: '0xD09f8B5c6050f3C01a68E9de54b6318F0d3b316a',
        nick_name: 'BEP20BlockchainTransfer',
      },
    ],
    RU: [
      {
        level: 2,
        bep20address: '0xD09f8B5c6050f3C01a68E9de54b6318F0d3b316a',
        nick_name: 'BEP20BlockchainTransfer',
      },
    ],
  },
  cases: {
    minimum_amount: {
      level: 2,
      activated: true,
      data: {
        amount: {
          USD: 1,
        },
      },
    },
    maximum_amount: {
      level: 2,
      activated: true,
      data: {
        amount: {
          USD: 99999999,
        },
      },
    },
    valid_amount: {
      level: 1,
      activated: true,
      data: {
        amount: {
          USD: 10,
        },
      },
    },
    component_assertion: {
      level: 2,
      activated: true,
    },
  },
};

//Covered for Android
output.about_us = {
  cases: {
    about_us: {
      level: 3,
      activated: true,
    },
    privacy_policy: {
      level: 3,
      activated: true,
    },
    terms_conditions: {
      level: 3,
      activated: true,
    },
    fees: {
      level: 3,
      activated: true,
    },
  },
  tests: {
    AE: {
      level: 3,
    },
    IN: {
      level: 3,
    },
  },
};

//Covered for iOS and Android
output.deeplinking = {
  cases: {
    // cases to be added here if any
  },
  tests: {
    AE: [
      {
        level: 3,
        url: `${output.meta.scheme}App/TopUp/TopUpOverviewScreen/`,
        element: 'Top-up',
      },
      {
        level: 3,
        url: `${output.meta.scheme}App/Home/Cards/`,
        element: '+ New card',
      },
      {
        level: 3,
        url: `${output.meta.scheme}App/Home/Cards/Card/9898`,
        element: '.*9898*.',
      },
      // {
      //   level: 3,
      //   url: `${output.meta.scheme}App/CardsManagement/RequestPhysicalCard`,
      //   element: 'Pricing',
      // },
      // {
      //   level: 3,
      //   url: `${output.meta.scheme}App/CardsManagement/CardPhysicalActivateScreen`,
      //   element: 'Pricing',
      // },
      // { level: 3, url: `${output.meta.scheme}App/Home/Accounts/`, element: 'Send' },
      // { level: 1, url: `${output.meta.scheme}App/Home/Cards/`, element: '+ New card' },
      // { level: 1, url: `${output.meta.scheme}App/Home/Cards/3911/`, element: '+ New card' },
      // { level: 1, url: `${output.meta.scheme}App/Settings/SettingsScreen/`, element: 'Settings' },
      // { level: 1, url: `${output.meta.scheme}App/Settings/VerificationScreen/`, element: 'Document details' },
      // { level: 1, url: `${output.meta.scheme}App/AboutUsScreen/ABOUT_US/`, element: 'Pyypl – it’s your money' },
      // { level: 1, url: `${output.meta.scheme}App/Settings/PrivacyPolicyScreen/PRIVACY_POLICY/`, element: 'Privacy policy' },
      // { level: 1, url: `${output.meta.scheme}App/Settings/TermsConditionScreen/TERMS_AND_CONDITIONS/`, element: 'PYYPL CUSTOMER TERMS OF USE' },
      // { level: 1, url: `${output.meta.scheme}App/FeesWebViewScreen/`, element: 'Top up (incl. VAT)' },
      // { level: 1, url: `${output.meta.scheme}App/Settings/FeesWebViewScreen/VirtualCardFee`, element: 'Fees' },
      // { level: 1, url: `${output.meta.scheme}App/Settings/Profile/`, element: 'Edit Profile' },
      // { level: 1, url: `${output.meta.scheme}App/Settings/ProfilePictureScreen/`, element: 'Profile picture' },
      // { level: 1, url: `${output.meta.scheme}App/Settings/ProfileNickNameScreen/`, element: 'Change name' },
      // { level: 1, url: `${output.meta.scheme}App/Settings/ProfileLanguageScreen/`, element: 'Language' },
      // { level: 1, url: `${output.meta.scheme}App/ProfileEmailScreen/`, element: 'Email' },
      // { level: 1, url: `${output.meta.scheme}App/Settings/PasscodeChange/`, element: 'Change Passcode' },
      // { level: 1, url: `${output.meta.scheme}App/Settings/CloseAccountScreen/`, element: 'Leave' },
      // { level: 1, url: `${output.meta.scheme}App/Help/HelpScreen/`, element: 'Help' },
      // { level: 1, url: `${output.meta.scheme}App/ReportBug/ReportBugScreen/`, element: 'Report a bug' },
      // { level: 1, url: `${output.meta.scheme}App/AppInbox/AppInboxScreen/`, element: 'Notifications' },
      // { level: 1, url: `${output.meta.scheme}App/Invite/UserInviteFriendScreen/`, element: 'Invite a friend and get paid' },
      // { level: 1, url: `${output.meta.scheme}App/AddMoney/AddMoneyOverview/`, element: 'Top-up', },
      // { level: 1, url: `${output.meta.scheme}App/AddMoney/AddMoneyCardDetailsCheckout/CHECKOUT_DEBIT_CARD/`, element: 'Card details' },
      // { level: 1, url: `${output.meta.scheme}App/AddMoney/AddMoneyCardDetailsStripe/STRIPE_DEBIT_CARD/`, element: 'Card details' },
      // { level: 1, url: `${output.meta.scheme}App/AddMoney/AddMoneyIntroduction/CASH/`, element: 'Top-up locations near you' },
      // { level: 1, url: `${output.meta.scheme}App/AddMoney/AddMoneyIntroduction/QR_CODE/`, element: 'Top-up with voucher' },
      // { level: 1, url: `${output.meta.scheme}App/AddMoney/AddMoneyIntroduction/BINANCE_PAY/`, element: 'Top-up your wallet using USDT via Pyypl Kenya' },
      // { level: 1, url: `${output.meta.scheme}App/AddMoney/AddMoneyBankTransfersOverview/BANK_TRANSFER/`, element: 'Bank transfer' },
      // { level: 1, url: `${output.meta.scheme}App/AddMoney/AddMoneyBankTransfersHistory/BANK_TRANSFER/`, element: 'Bank transfer requests' },
      // { level: 1, url: `${output.meta.scheme}App/AddMoney/AddMoneyManualAmount/BANK_TRANSFER/`, element: 'How much would you like to top up' },
      // { level: 1, url: `${output.meta.scheme}App/AddMoney/AddMoneyPhoneDetailsMPESA/MPESA/`, element: 'Add wallet' },
      // { level: 1, url: `${output.meta.scheme}App/AddMoney/AddMoneyBinance/BINANCE_PAY/`, element: 'Top-up' },
      // { level: 1, url: `${output.meta.scheme}App/AddMoney/KioskScannerSuccess/CASH/`, element: 'Top-up' },
      // { level: 1, url: `${output.meta.scheme}App/AddMoney/AddMoneyFlutterwave/FLUTTERWAVE_MOBILE_MONEY_GH/`, element: 'Flutterwave' },
      // { level: 1, url: `${output.meta.scheme}App/Transactions/TransactionsScreen/`, element: 'Transactions' },
      // { level: 1, url: `${output.meta.scheme}App/Transactions/TransactionDetailsScreen/bd9b2d97-505d-4eff-a2ff-4b630af9ec35/`, element: 'Transaction Details' },
      // { level: 1, url: `${output.meta.scheme}App/SendMoney/SendMoneyAmountsScreen/INTERNATIONAL_TRANSFER/`, element: 'Amount' },
      // { level: 1, url: `${output.meta.scheme}App/SendMoney/SendMoneyAmountsScreen/LOCAL_TRANSFER/`, element: 'Amount' },
      // { level: 1, url: `${output.meta.scheme}App/SendMoney/SendMoneyAmountsScreen/MOBILE_WALLETS/`, element: 'Amount' },
      // { level: 1, url: `${output.meta.scheme}App/SendMoney/SendMoneyAmountsScreen/BLOCK_CHAIN_TRANSFER`, element: 'Enter your BEP20 address' },
      // { level: 1, url: `${output.meta.scheme}App/SendMoney/SendMoneyContactScreen/false/pyypl/false/false/`, element: 'Allow' },
    ],
  },
};

//Covered for Android, for AE and IN users
output.create_account = {
  cases: {
    new_account_details: {
      level: 3,
      data: {
        nickname: 'John Doe',
      },
    },
  },
  tests: {
    AE: {
      level: 3,
      new_phone_number: generatePhoneNumber(
        output.user.country.countryCode,
      ).slice(-9), //"527865998",
    },
    IN: {
      level: 3,
      new_phone_number: generatePhoneNumber(
        output.user.country.countryCode,
      ).slice(-10), // "6767656565"
    },
  },
};

//Covered for Android for AE users
output.lean_bank = {
  cases: {
    // cases to be added here if any
  },
  tests: {
    AE: {
      level: 3,
      username: 'mayolajones',
      password: 'FOTfFevIk',
      otp: 1111,
    },
  },
};

output.mercuryo = {
  cases: {
    // cases to be added here if any
  },
  tests: {
    IN: {
      level: 3,
      TRC20: 'TNqb5vAx1mAnqZ2eE6U6uvBD57XWr9rGQM',
    },
  },
};

output.gift_cards = {
  cases: {
    // cases to be added here if any
  },
  tests: {
    AE: [
      {
        level: 3,
        country: 'United Arab Emirates',
        country_code: 'AE',
        gift: 'Amazon',
        amount_id: '351',
        currency: 'AED',
      }, //UAE
      {
        level: 2,
        country: 'France',
        country_code: 'FR',
        gift: 'Spotify',
        amount_id: '1192',
        currency: 'EUR',
      }, // France
      {
        level: 2,
        country: 'Germany',
        country_code: 'DE',
        gift: 'Google Play',
        amount_id: '187',
        currency: 'EUR',
      }, // Germany
      {
        level: 2,
        country: 'Italy',
        country_code: 'IT',
        gift: 'Apple',
        amount_id: '594',
        currency: 'EUR',
      }, // Italy
      {
        level: 3,
        country: 'Turkey',
        country_code: 'TR',
        gift: 'Netflix',
        amount_id: '1406',
        currency: 'TRY',
      }, //Turkey
    ],
  },
};

output.change_passcode = {
  cases: {
    passcode: {
      new_passcode: '0000',
    },
  },
  tests: {
    AE: {
      level: 3,
    },
    IN: {
      level: 3,
    },
  },
};

output.verification = {
  cases: {
    // TODO
  },
  tests: {
    AE: {
      level: 3,
    },
    IN: {
      level: 3,
    },
  },
};

output.sourceـof_funds = {
  cases: {
    data: {
      set1: {
        occupation1: 'profession1',
        sector1: 'coreText-sector1-value',
        sub_sector1: 'coreText-subSector1:0-value',
        income_range1: 'incomeRangeFrom250100To500000',
        turnover1: 'turnoverRangeFrom250100To500000',
        source1: 'sourceOfFunds1',
      },
      set2: {
        occupation2: 'profession0',
        sector2: 'coreText-sector0-value',
        sub_sector2: 'subSector0:0',
        income_range2: 'incomeRangeFrom1500000Tonull',
        turnover2: 'turnoverRangeFrom1500000Tonull',
        source2: 'sourceOfFunds0',
      },
    },
  },
  tests: {
    AE: {
      level: 3,
    },
  },
};

output.notifications = {
  cases: {
    // TODO
  },
  tests: {
    AE: {
      level: 3,
    },
  },
};
