appId: com.pyypl.${MAESTRO_ENV}
tags:
  - AE
onFlowStart:
  - runScript: constants.js

  - evalScript: ${output.tests=output.change_language.tests[output.user.country.countryCode]}

  - tapOn:
      id: 'BackButton'
      optional: true
  - tapOn:
      id: 'BackButton'
      optional: true
  - tapOn:
      id: 'BackButton'
      optional: true
  - runFlow:
      when:
        notVisible:
          id: 'wallet-feature-Send'
      commands:
        - runFlow: ./subflows/app/launch-cold.yaml
        - runFlow:
            file: ./subflows/auth/sign-in.yaml
            env:
              COUNTRY_CODE: ${output.user.country.countryCode}
              CODE: ${output.user.country.value}
              COUNTRY_NAME: ${output.user.country.countryName}
              PHONE_NUMBER: ${output.user.phone_number}
              PASSCODE: ${output.user.passcode}
---
- repeat:
    while:
      true: ${output.tests.length > 0}
    commands:
      - evalScript: ${output.test=output.tests[0]}
      - runFlow:
          file: ./subflows/settings/change-language.yaml
          env:
            TEST_LEVEL: ${output.test.level}
            LANGUAGE: ${output.test.language}
            PASSCODE: ${output.user.passcode}
      - evalScript: ${output.tests.shift()}
