appId: com.pyypl.${MAESTRO_ENV}
tags:
  - AE
  - INTL
  - DISABLED
onFlowStart:
  - runScript: constants.js

  - evalScript: ${ output.tests=output.notifications.tests[output.user.country.countryCode] }

  - tapOn:
      id: 'BackButton'
      optional: true
  - tapOn:
      id: 'BackButton'
      optional: true
  - tapOn:
      id: 'BackButton'
      optional: true
  - runFlow:
      when:
        notVisible:
          id: 'wallet-feature-Send'
      commands:
        - runFlow: ./subflows/app/launch-cold.yaml
        - runFlow:
            file: ./subflows/auth/sign-in.yaml
            env:
              COUNTRY_CODE: ${output.user.country.countryCode}
              CODE: ${output.user.country.value}
              COUNTRY_NAME: ${output.user.country.countryName}
              PHONE_NUMBER: ${output.user.phone_number}
              PASSCODE: ${output.user.passcode}
---
- runFlow:
    file: ./subflows/settings/notifications.yaml
    env:
      OCCUPATION1: ${ output.set1.occupation1 }
