appId: com.pyypl.${MAESTRO_ENV}
tags:
  - DISBALED
onFlowStart:
  - runScript: constants.js

  - evalScript: ${output.tests=output.profile.tests[output.user.country.countryCode]}

  - tapOn:
      id: 'BackButton'
      optional: true
  - tapOn:
      id: 'BackButton'
      optional: true
  - tapOn:
      id: 'BackButton'
      optional: true
  - runFlow:
      when:
        notVisible:
          id: 'wallet-feature-Send'
      commands:
        - runFlow: ./subflows/app/launch-cold.yaml
        - runFlow:
            file: ./subflows/auth/sign-in.yaml
            env:
              COUNTRY_CODE: ${output.user.country.countryCode}
              CODE: ${output.user.country.value}
              COUNTRY_NAME: ${output.user.country.countryName}
              PHONE_NUMBER: ${output.user.phone_number}
              PASSCODE: ${output.user.passcode}
---
- runFlow:
    file: ./subflows/settings/intl-help-section.yaml
    env:
      PASSCODE: ${output.user.passcode}
      PHONE_NUMBER: ${output.user.phone_number}
      FULL_PHONE_NUMBER: ${output.user}
      NAME: ${output.profile.profile_data.name}
      COUNTRY_NAME: ${output.user.country.countryName}
